REPORT ZGUL_EGITIM_7.

TYPES: BEGIN OF gty_ekipman,
  EKIP_ID TYPE ZGUL_EKIPID_DE,
  EKIP_AD TYPE ZGUL_EKIPAD_DE,
  EKIP_STOK TYPE ZGUL_STOK_DE,
  EKIP_EN TYPE ZGUL_EN_DE,
  EKIP_BOY TYPE ZGUL_BOY_DE,
  END OF gty_ekipman.

DATA: gt_ekipman TYPE TABLE OF gty_ekipman.

START-OF-SELECTION.

*SELECT * FROM ZGUL_EGT_01
*  INTO CORRESPONDING FIELDS OF TABLE gt_ekipman.

*SELECT * FROM ZGUL_EGT_01
*  INNER JOIN ZGUL_EGT_02 ON ZGUL_EGT_02~EKIP_ID eq ZGUL_EGT_01~EKIP_ID
*  INTO CORRESPONDING FIELDS OF TABLE gt_ekipman.

*SELECT
*  ZGUL_EGT_01~EKIP_ID
*  ZGUL_EGT_01~EKIP_AD
*  ZGUL_EGT_02~EKIP_STOK
*  FROM ZGUL_EGT_01
*  INNER JOIN ZGUL_EGT_02 ON ZGUL_EGT_02~EKIP_ID eq ZGUL_EGT_01~EKIP_ID
*  INTO CORRESPONDING FIELDS OF TABLE gt_ekipman.


*SELECT
*  Z1~EKIP_ID
*  Z1~EKIP_AD
*  Z2~EKIP_STOK
*  FROM ZGUL_EGT_01 AS Z1
*  JOIN ZGUL_EGT_02 AS Z2 ON Z1~EKIP_ID eq Z2~EKIP_ID
*  INTO CORRESPONDING FIELDS OF TABLE gt_ekipman.

*SELECT
*  Z1~EKIP_ID
*  Z1~EKIP_AD
*  Z2~EKIP_STOK
*  FROM ZGUL_EGT_01 AS Z1
*  LEFT JOIN ZGUL_EGT_02 AS Z2 ON Z1~EKIP_ID eq Z2~EKIP_ID
*  INTO CORRESPONDING FIELDS OF TABLE gt_ekipman.

*SELECT
*  Z1~EKIP_ID
*  Z1~EKIP_AD
*  Z2~EKIP_STOK
*  FROM ZGUL_EGT_01 AS Z1
*  LEFT OUTER JOIN ZGUL_EGT_02 AS Z2 ON Z1~EKIP_ID eq Z2~EKIP_ID
*  INTO CORRESPONDING FIELDS OF TABLE gt_ekipman.

*SELECT
*  Z2~EKIP_ID,
*  Z1~EKIP_AD,
*  Z2~EKIP_STOK
*  FROM ZGUL_EGT_01 AS Z1
*  RIGHT JOIN ZGUL_EGT_02 AS Z2 ON Z1~EKIP_ID eq Z2~EKIP_ID
*  INTO CORRESPONDING FIELDS OF TABLE @gt_ekipman.

*SELECT
*  Z2~EKIP_ID,
*  Z1~EKIP_AD,
*  Z2~EKIP_STOK
*  FROM ZGUL_EGT_01 AS Z1
*  RIGHT OUTER JOIN ZGUL_EGT_02 AS Z2 ON Z1~EKIP_ID eq Z2~EKIP_ID
*  INTO CORRESPONDING FIELDS OF TABLE @gt_ekipman.

*SELECT
*  Z1~EKIP_ID
*  Z1~EKIP_AD
*  Z2~EKIP_STOK
*  Z3~EKIP_EN
*  Z3~EKIP_BOY
*  FROM ZGUL_EGT_01 AS Z1
*  INNER JOIN ZGUL_EGT_02 AS Z2 ON Z1~EKIP_ID eq Z2~EKIP_ID
*  INNER JOIN ZGUL_EGT_03 AS Z3 ON Z3~EKIP_ID eq Z1~EKIP_ID
*  INTO CORRESPONDING FIELDS OF TABLE gt_ekipman.

SELECT
  Z1~EKIP_ID
  Z1~EKIP_AD
  Z2~EKIP_STOK
  Z3~EKIP_EN
  Z3~EKIP_BOY
  FROM ZGUL_EGT_01 AS Z1
  INNER JOIN ZGUL_EGT_02 AS Z2 ON Z1~EKIP_ID eq Z2~EKIP_ID
  LEFT JOIN ZGUL_EGT_03 AS Z3 ON Z3~EKIP_ID eq Z1~EKIP_ID
  INTO CORRESPONDING FIELDS OF TABLE gt_ekipman.
BREAK-POINT.