REPORT ZGUL_EGITIM_9.

TABLES: ZGUL_PERS_T1.
DATA: gv_psrsoyad TYPE ZGUL_PERSSOYAD_DE.

PARAMETERS: p_num1 TYPE int4,
            p_PERSAD TYPE ZGUL_PERSAD_DE.

SELECT-OPTIONS: s_perssd FOR gv_psrsoyad,
                s_perscn FOR ZGUL_PERS_T1-PERS_CINS.

PARAMETERS: p_cbox1 AS CHECKBOX.

SELECTION-SCREEN BEGIN OF BLOCK bl1 WITH FRAME TITLE text-001.
PARAMETERS: p_rad1 RADIOBUTTON GROUP gr1,
            p_rad2 RADIOBUTTON GROUP gr1,
            p_rad3 RADIOBUTTON GROUP gr1.
SELECTION-SCREEN END OF BLOCK bl1.

SELECTION-SCREEN BEGIN OF BLOCK bl2 WITH FRAME TITLE text-002.
PARAMETERS: p_rad4 RADIOBUTTON GROUP gr2,
            p_rad5 RADIOBUTTON GROUP gr2.
SELECTION-SCREEN END OF BLOCK bl2.